# ---------------------------------------------------------------------------
# SAFETravellers API — Docker image
#
# Base: ubuntu:24.04 — matches the build environment of the C++ binaries.
#
# Runtime dependencies of the pre-built binaries:
#   • libtfhe-spqlios-avx.so  — copied from all_libs/tfhe/build/libtfhe/
#   • libcrypto.so.3          — installed via system package libssl3t64
#   • libstdc++.so.6, libc.so.6, libgcc_s.so.1, libm.so.6 — in base image
#
# Build context is kept small by .dockerignore (only ~40 MB transferred).
# ---------------------------------------------------------------------------

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# --------------------------------------------------------------------------
# 1. System runtime packages
# --------------------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        libssl3t64 \
    && rm -rf /var/lib/apt/lists/*

# --------------------------------------------------------------------------
# 2. TFHE shared library  (the only non-system .so the binaries need)
# --------------------------------------------------------------------------
COPY all_libs/tfhe/build/libtfhe/libtfhe-spqlios-avx.so /usr/local/lib/
RUN ldconfig

# --------------------------------------------------------------------------
# 3. Application layout
# --------------------------------------------------------------------------
WORKDIR /app

# Pre-built C++ binaries
COPY bin/HESysInit bin/Register bin/EncBio bin/Verify bin/

# Python API
COPY api/requirements.txt api/requirements.txt
RUN pip3 install --no-cache-dir --break-system-packages -r api/requirements.txt
COPY api/server.py api/server.py

# --------------------------------------------------------------------------
# 4. Static system data generated by HESysInit
#    (FHE parameters, computation keys, traveller key material)
#    These are baked into the image so the service is ready without
#    running /api/v1/init.  Re-init by calling POST /api/v1/init at any
#    time — results will be written to /app/data and persist if the
#    data/ directory is backed by a volume.
# --------------------------------------------------------------------------
COPY data/System_Parameters/ data/System_Parameters/
COPY data/HEComp/             data/HEComp/
COPY data/Traveller/          data/Traveller/

# --------------------------------------------------------------------------
# 5. Runtime data directories (populated by API calls at run time)
#    These are intentionally empty; mount Docker volumes here to persist
#    biometric registrations and test biometric uploads across restarts.
# --------------------------------------------------------------------------
RUN mkdir -p \
        data/CountryDB/Reg_Biometrics_Enc \
        data/E-Gate/Test_Bio_Enc \
        tmp

# --------------------------------------------------------------------------
# 6. Runtime configuration
#    Override these with -e / --env-file / docker-compose environment:
#      SAFE_API_KEY  — shared secret for X-Api-Key header (required)
#      SAFE_API_HOST — bind address (default 0.0.0.0)
#      SAFE_API_PORT — listen port  (default 8080)
# --------------------------------------------------------------------------
ENV SAFE_API_HOST="0.0.0.0" \
    SAFE_API_PORT="8080" \
    SAFE_API_KEY=""

EXPOSE 8080

CMD ["python3", "api/server.py"]
