#include <cstddef>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <ctime>
#include <iomanip>
#include <time.h>
#include <filesystem>

// SEAL
#include "seal/seal.h"

// TFHE
#include "tfhe.h"


#include "utils.h"
#include "dataIO.h"
#include "token.h"
#include "keysUser.h"
#include "constants.h"
using namespace std;
using namespace seal;
namespace fs = std::filesystem;

//  inline void print_parameters(const seal::SEALContext &context)
// {
//     auto &context_data = *context.key_context_data();

//     /*
//     Which scheme are we using?
//     */
//     std::string scheme_name;
//     switch (context_data.parms().scheme())
//     {
//     case seal::scheme_type::bfv:
//         scheme_name = "BFV";
//         break;
//     case seal::scheme_type::ckks:
//         scheme_name = "CKKS";
//         break;
//     case seal::scheme_type::bgv:
//         scheme_name = "BGV";
//         break;
//     default:
//         throw std::invalid_argument("unsupported scheme");
//     }
//     std::cout << "/" << std::endl;
//     std::cout << "| Encryption parameters :" << std::endl;
//     std::cout << "|   scheme: " << scheme_name << std::endl;
//     std::cout << "|   poly_modulus_degree: " << context_data.parms().poly_modulus_degree() << std::endl;
    
//     /*
//     Print the size of the true (product) coefficient modulus.
//     */
//     std::cout << "|   coeff_modulus size: ";
//     std::cout << context_data.total_coeff_modulus_bit_count() << " (";
//     auto coeff_modulus = context_data.parms().coeff_modulus();
//     std::size_t coeff_modulus_size = coeff_modulus.size();
//     for (std::size_t i = 0; i < coeff_modulus_size - 1; i++)
//     {
//         std::cout << coeff_modulus[i].bit_count() << " + ";
//     }

//     std::cout << coeff_modulus.back().bit_count();
//     std::cout << ") bits" << std::endl;
//     for (std::size_t i = 0; i < coeff_modulus_size - 1; i++)
//     {
//         std::cout << coeff_modulus[i].value() << " + ";
//     }
//     //std::cout << "|   coeff_modulus: " << coeff_modulus << std::endl;

//     /*
//     For the BFV scheme print the plain_modulus parameter.
//     */
//     if (context_data.parms().scheme() == seal::scheme_type::bfv)
//     {
//         std::cout << "|   plain_modulus: " << context_data.parms().plain_modulus().value() << std::endl;
//     }

//     std::cout << "\\" << std::endl;
// }
int main(int argc, char *argv[])
{
    if (argc < 2) {
    std::cerr << "Usage: " << argv[0] << " <Input Registration Biometric folder> " << " <Output Registration Biometric folder> "<<  std::endl;
    return 1;
  }
  //UserID::generateID(); We either use this ID or the ID generated by the SSI wallet. 
  
  // There needs to be check if this user has been already registered. If yes, then no need to register again.

  //// ******** INSERT CODE HERE FOR CHECKING IF USER IS ALREADY REGISTERED ******** ////

  // Generating User Keys
  // cout << "Generating User Keys..." << endl;
  // UserKeyGen::generateUserKeys();



  // Read the SEAL parameters from the file

 std::ifstream bin_sealparam_handler("../data/System_Parameters/sealparam.txt", std::ios::in | std::ios::binary);
    if (!bin_sealparam_handler) {
        std::cerr << "Seal param file did not open!" << std::endl;
        return 1;
    }

   // Read the parameters from the file
    EncryptionParameters parms(scheme_type::bfv);
    parms.load(bin_sealparam_handler);
    bin_sealparam_handler.close();

    if (!bin_sealparam_handler.good()) {
        std::cerr << "Error occurred during reading the seal param binary file!" << std::endl;
        return 2;
    }

SEALContext context(parms);

PublicKey init_public_key;

  filebuf bin_sealpubK_handler;
  if (bin_sealpubK_handler.open("../data/Keys/sealpubK.txt", ios::in | ios::binary))
    { //std::cout << "In here" << '\n';
    istream is(&bin_sealpubK_handler);
    init_public_key.load(context,is);
    bin_sealpubK_handler.close();}

Encryptor init_encryptor(context, init_public_key);


//Some necesary parameters for the Biometrics
const int N = parms.poly_modulus_degree();
//cout << "Value of N: " << N << endl;
const uint64_t p = parms.plain_modulus().value();
const int precision = Constants::PRECISION;
const int vector_size = Constants::VECTOR_SIZE;
  if (vector_size > N)
  {
    std::cout << "The size of N has to be greater than that of the Biometrics vectors" << '\n';
    return -1;
  }

  /**
  * Read the initial Plaintext models, i.e. the embeddings of the biometrics as SEAL Plaintexts
  */

  cout << "Reading the Biometrics, encrypting and registering" << endl;
  clock_t read_bio_start = clock();
  

//   std::string fileName_model_f = "../data/Traveller/" + std::string(argv[1]);
//   std::string fileName_model_to = "../data/CountryDB/Reg_Biometrics_Enc/";
  
  std::string folderName_model_f = std::string(argv[1]);
  std::string folderName_model_to = std::string(argv[2]);

  // Check if input folder exists
  if (!fs::exists(folderName_model_f)) {
    std::cerr << "Error: Input folder does not exist: " << folderName_model_f << std::endl;
    return 1;
  }
  
  // Read all files from the input folder
  std::vector<std::string> biometric_files;
  for (const auto & entry : fs::directory_iterator(folderName_model_f)) {
    if (fs::is_regular_file(entry)) {
      biometric_files.push_back(entry.path().filename().string());
    }
  }
  
  if (biometric_files.empty()) {
    std::cerr << "Error: No files found in input folder: " << folderName_model_f << std::endl;
    return 1;
  }
  
  // Display found files
  cout << "Found " << biometric_files.size() << " biometric file(s) in " << folderName_model_f << ":" << endl;
  for (const auto & file : biometric_files) {
    cout << "  - " << file << endl;
  }
  cout << endl;
  
  // Create output directory if it doesn't exist
  if (!fs::exists(folderName_model_to)) {
    fs::create_directories(folderName_model_to);
    cout << "Created output directory: " << folderName_model_to << endl;
  }
  //  cout << "The precision is set to " << precision << " and the vector size is set to " << vector_size  << "and the modulus is set to " << p << endl;

  // Process each biometric file
  for (const auto & fileName_model_f : biometric_files) {
    cout << "Processing: " << fileName_model_f << endl;
    std::string fullName_model_f = folderName_model_f + "/" + fileName_model_f;

    std::string fileName_model_to = folderName_model_to + "/" + fileName_model_f + "_enc/";
    fs::create_directory(fileName_model_to);
    dataIO::EncryptF2F(fileName_model_to, fullName_model_f, init_encryptor, vector_size, precision, p, 0);
    cout << "  ✓ Successfully encrypted and registered" << endl;
  }





cout << "***************************************************" << endl;
cout << "*     Successfully Registered User Biometrics     *" << endl;
cout << "***************************************************" << endl;
//double read_bio_time = double(read_bio_end - read_bio_start) / CLOCKS_PER_SEC;
// double enc_bio_time = double(enc_bio_end - enc_bio_start) / CLOCKS_PER_SEC;
// cout << "Time for reading the Biometrics: " << read_bio_time << " seconds" << endl;
// cout << "Time for encrypting and registering the Biometrics: " << enc_bio_time << " seconds" << endl;


  return 0;
}